name: CI

on:
  push:
    branches: [ main ] # O workflow será executado em cada "push" na branch "main".
  pull_request:
    branches: [ main ] # O workflow será executado em cada "pull request" direcionado à branch "main".

permissions:
  contents: write  # Permite escrever no conteúdo do repositório (código, arquivos)
  pages: write     # Permite deploy no GitHub Pages (se você estiver usando)
  id-token: write  # Necessário para alguns tipos de autenticação com provedores externos

jobs:
  build:

    runs-on: ubuntu-latest # Define o sistema operacional para executar o workflow.

    steps:
      - uses: actions/checkout@v3 # Faz o "checkout" do código do repositório para a máquina virtual.

      - name: Executar testes
        run: |
          echo "Nenhum teste implementado ainda. Adicione testes em script.js!"
          echo "Podemos adicionar testes com Jest ou Cypress no futuro."
          echo "Testes simulados aprovados"
          exit 0 # Simula testes passando

      - name: Deploy para GitHub Pages
        if: github.ref == 'refs/heads/main' # Só executa o deploy quando o commit for na branch main.
        uses: actions/deploy-pages@v2
        with:
          folder: . # Diretório a ser deployado (raiz do repositório neste caso)